apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_HOST: cG9zdGdyZXMtYmFja3N0YWdl
  POSTGRES_PORT: NTQzMg==  # "5432" codificado em base64
  AUTH_GITHUB_CLIENT_ID: Mude aqui
  AUTH_GITHUB_CLIENT_SECRET: Mude aqui

