app:
  title: Uday Backstage Produção
  baseUrl: http://localhost:7007
  listen:
    host: 0.0.0.0
  backend:
    baseUrl: http://localhost:7007
    listen:
      host: 0.0.0.0

database:
  client: pg
  connection:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

catalog:
  rules:
    - allow: [Group, User, Component, System, API, Resource, Location]
  locations:
    - type: file
      target: identidades/usuarios.yaml
    - type: file
      target: identidades/grupos.yaml
