apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-local
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.20-192.168.1.50

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advert-local
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool-local