# tool/.github/workflows/cd.yaml
name: Deploy via ArgoCD

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      argocd_server:
        required: true
        type: string
      argocd_port:
        required: false
        type: string
        default: "9092"
      argocd_username:
        required: false
        type: string
        default: "admin"
      image_tag:
        required: false
        type: string
    secrets:
      argocd_password:
        required: true
      repo_token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download argocd CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd

      - name: ArgoCD Login
        run: |
          argocd login ${{ inputs.argocd_server }}:${{ inputs.argocd_port }} \
            --insecure \
            --grpc-web \
            --username ${{ inputs.argocd_username }} \
            --password ${{ secrets.argocd_password }}

      - name: Add repository credentials
        run: |
          argocd repo rm https://github.com/uday-platform-idp-org/${{ inputs.app_name }} || echo "Repository not found"
          argocd repo add https://github.com/uday-platform-idp-org/${{ inputs.app_name }} \
            --username oauth2 \
            --password ${{ secrets.repo_token }} \
            --insecure-skip-server-verification

      - name: Create application if not exists
        run: |
          if ! argocd app get ${{ inputs.app_name }} >/dev/null 2>&1; then
            argocd app create ${{ inputs.app_name }} \
              --repo https://github.com/uday-platform-idp-org/${{ inputs.app_name }} \
              --path helm-charts/uday-app \
              --dest-server https://kubernetes.default.svc \
              --dest-namespace uday-app \
              --sync-policy automated \
              --auto-prune \
              --self-heal
          fi

      - name: Checkout repository
        run: |
          git clone https://oauth2:${{ secrets.repo_token }}@github.com/uday-platform-idp-org/${{ inputs.app_name }}.git infra
          cd infra
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://oauth2:${{ secrets.repo_token }}@github.com/uday-platform-idp-org/${{ inputs.app_name }}.git

      - name: Update image tag in Helm values.yaml
        run: |
          cd infra
          if [ -n "${{ inputs.image_tag }}" ]; then
            sed -i "s/tag: .*/tag: ${{ inputs.image_tag }}/" helm-charts/uday-app/values.yaml
          fi

      - name: Commit and Push
        run: |
          cd infra
          if [ -n "${{ inputs.image_tag }}" ] && ! git diff --quiet; then
            git add .
            git commit -m "Update image tag to ${{ inputs.image_tag }}"
            git push origin main
          fi

      - name: Sync and Wait
        run: |
          argocd app sync ${{ inputs.app_name }}
          argocd app wait ${{ inputs.app_name }} --timeout 180