name: Build and Push Image

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      dockerhub_username:
        required: true
        type: string
    secrets:
      dockerhub_token:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}
    
    steps:
      - uses: actions/checkout@v3
      - id: set-tag
        run: |
          image_tag=$(echo $GITHUB_SHA | cut -c1-7)
          echo "tag=${image_tag}" >> $GITHUB_OUTPUT
        shell: bash
      - uses: docker/login-action@v2
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      - run: |
          docker build -t ${{ inputs.dockerhub_username }}/${{ inputs.app_name }}:${{ steps.set-tag.outputs.tag }} .
          docker push ${{ inputs.dockerhub_username }}/${{ inputs.app_name }}:${{ steps.set-tag.outputs.tag }}
        shell: bash
