# tool/.github/workflows/ci.yaml
name: Build and Push Image

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true
    outputs:
      image_tag:
        description: "Generated image tag"
        value: ${{ jobs.build-and-push.outputs.image_tag }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}
    
    steps:
      - uses: actions/checkout@v3

      - id: set-tag
        run: |
          image_tag="sha-$(echo $GITHUB_SHA | cut -c1-7)"
          echo "tag=$image_tag" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      - run: |
          docker build -t ${{ secrets.dockerhub_username }}/${{ inputs.app_name }}:${{ steps.set-tag.outputs.tag }} .
          docker push ${{ secrets.dockerhub_username }}/${{ inputs.app_name }}:${{ steps.set-tag.outputs.tag }}
        shell: bash